services:
  auth:
    build:
      context: ./modules/auth
      dockerfile: Dockerfile.prod
    image: chetapp-auth:prod
    ports:
      - "8080:8080"
    restart: unless-stopped
  krakend:
    build:
      context: ./krakend
    image: chetapp-krakend:prod
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  auth-db-data:
