services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: chetapp-auth
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - chetapp-network
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chetapp-auth-db

  fleet-management:
    build:
      context: ./fleet-management
      dockerfile: Dockerfile
    container_name: chetapp-fleet-management
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      chetapp-fleet-management-db:
        condition: service_healthy
    networks:
      - chetapp-network
    environment:
      - DB_HOST=chetapp-fleet-management-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chetapp-fleet-management-db

  krakend:
    build:
      context: ./krakend
      dockerfile: Dockerfile
    container_name: chetapp-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - chetapp-network
    depends_on:
      - auth

  auth-db:
    image: postgres:17-bullseye
    container_name: chetapp-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chetapp-auth-db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chetapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chetapp-fleet-management-db:
    image: postgres:17-bullseye
    container_name: chetapp-fleet-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chetapp-fleet-management-db
    ports:
      - "5434:5432"
    volumes:
      - fleet-management-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chetapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: chetapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@chetapp.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - chetapp-network
    depends_on:
      - auth-db
      - chetapp-fleet-management-db

volumes:
  pgadmin-data:
    driver: local
  auth-db-data:
    driver: local
  fleet-management-db-data:
    driver: local

networks:
  chetapp-network:
    driver: bridge
