services:
  auth:
    build:
      context: ./modules/auth
      dockerfile: Dockerfile
    image: chetapp-auth:dev
    env_file:
      - ./modules/auth/.env
    ports:
      - "8080:8080"
    depends_on:
      - auth-db
    networks:
      - chetapp-network

  auth-db:
    image: postgres:17-alpine
    container_name: chetapp-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chetapp-auth-db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - chetapp-network

  krakend:
    build:
      context: ./krakend
    image: chetapp-krakend:dev
    ports:
      - "8081:8080"
    depends_on:
      - auth
    networks:
      - chetapp-network

networks:
  chetapp-network:
    driver: bridge

volumes:
  auth-db-data:
